version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/localdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_REDIS_HOST: host.docker.internal
      SPRING_REDIS_PORT: 6379
